In [1]:
import numpy as np

print("----- 1. Broadcasting with Scalars -----")

arr = np.array([1, 2, 3, 4])
print("Array:", arr)
print("Shape:", arr.shape)

# Scalar broadcasting
result = arr + 10
print("After adding scalar 10:", result)


print("\n----- 2. Broadcasting Between 1D Arrays -----")

a = np.array([1, 2, 3])
b = np.array([10])   # size 1 → can broadcast

print("Array a:", a, "Shape:", a.shape)
print("Array b:", b, "Shape:", b.shape)

result = a + b
print("Result (a + b):", result)


print("\n----- 3. Broadcasting Between 2D and 1D Arrays -----")

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

print("Matrix:\n", matrix)
print("Matrix Shape:", matrix.shape)

print("Vector:", vector)
print("Vector Shape:", vector.shape)

# Broadcasting row-wise
result = matrix + vector
print("Result (matrix + vector):\n", result)


print("\n----- 4. Column-wise Broadcasting -----")

matrix2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

column_vector = np.array([[10], [20]])  # shape (2,1)

print("Matrix:\n", matrix2)
print("Matrix Shape:", matrix2.shape)

print("Column Vector:\n", column_vector)
print("Column Vector Shape:", column_vector.shape)

# Broadcasting column-wise
result = matrix2 + column_vector
print("Result (column-wise broadcast):\n", result)


print("\n----- 5. Broadcasting Rules Demonstration -----")

x = np.array([1, 2, 3])
y = np.array([[10], [20], [30]])

print("x Shape:", x.shape)
print("y Shape:", y.shape)

result = x + y
print("Result:\n", result)


print("\n----- 6. Incompatible Shapes Example -----")

a = np.array([1, 2, 3])
b = np.array([1, 2])

print("a Shape:", a.shape)
print("b Shape:", b.shape)

try:
    print(a + b)
except ValueError as e:
    print("Error:", e)


print("\n----- Broadcasting Demo Completed -----")

----- 1. Broadcasting with Scalars -----
Array: [1 2 3 4]
Shape: (4,)
After adding scalar 10: [11 12 13 14]

----- 2. Broadcasting Between 1D Arrays -----
Array a: [1 2 3] Shape: (3,)
Array b: [10] Shape: (1,)
Result (a + b): [11 12 13]

----- 3. Broadcasting Between 2D and 1D Arrays -----
Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix Shape: (2, 3)
Vector: [10 20 30]
Vector Shape: (3,)
Result (matrix + vector):
 [[11 22 33]
 [14 25 36]]

----- 4. Column-wise Broadcasting -----
Matrix:
 [[1 2 3]
 [4 5 6]]
Matrix Shape: (2, 3)
Column Vector:
 [[10]
 [20]]
Column Vector Shape: (2, 1)
Result (column-wise broadcast):
 [[11 12 13]
 [24 25 26]]

----- 5. Broadcasting Rules Demonstration -----
x Shape: (3,)
y Shape: (3, 1)
Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]

----- 6. Incompatible Shapes Example -----
a Shape: (3,)
b Shape: (2,)
Error: operands could not be broadcast together with shapes (3,) (2,) 

----- Broadcasting Demo Completed -----
