In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(arr1)

[1 2 3 4 5]


In [3]:
list2 = [[1, 2, 3],
         [4, 5, 6]]

arr2 = np.array(list2)

print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr1.shape)   # shape (dimensions)
print(arr1.dtype)   # data type

print(arr2.shape)
print(arr2.dtype)

(5,)
int64
(2, 3)
int64


In [5]:
arr = np.array([10, 20, 30])

print(arr + 5)   # add 5 to each element
print(arr * 2) 

[15 25 35]
[20 40 60]


In [6]:
list_data = [10, 20, 30]

print(list_data * 2)  # repeats list (not numeric multiply)

[10, 20, 30, 10, 20, 30]
