In [1]:
import numpy as np

# -----------------------
# 1D Array
# -----------------------
arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr1)
print("Shape:", arr1.shape)
print("Dimensions (ndim):", arr1.ndim)

# Access elements in 1D array
print("Element at index 0:", arr1[0])
print("Element at index 3:", arr1[3])

print("\n-----------------------\n")

# -----------------------
# 2D Array
# -----------------------
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Dimensions (ndim):", arr2.ndim)

# Access elements in 2D array
print("Element at row 0, col 0:", arr2[0][0])
print("Element at row 1, col 2:", arr2[1][2])
print("Element at row 2, col 1:", arr2[2][1])

print("\n-----------------------\n")

# -----------------------
# Visualization idea (printing structure)
# -----------------------
print("Row 0:", arr2[0])
print("Row 1:", arr2[1])
print("Row 2:", arr2[2])

1D Array: [10 20 30 40 50]
Shape: (5,)
Dimensions (ndim): 1
Element at index 0: 10
Element at index 3: 40

-----------------------

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions (ndim): 2
Element at row 0, col 0: 1
Element at row 1, col 2: 6
Element at row 2, col 1: 8

-----------------------

Row 0: [1 2 3]
Row 1: [4 5 6]
Row 2: [7 8 9]
